language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t godtaehee/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true godtaehee/react-test-app npm run test

after_success:
  - docker build -t godtaehee/docker-frontend ./frontend
  - docker build -t godtaehee/docker-backend ./backend
  - docker build -t godtaehee/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push godtaehee/docker-frontend
  - docker push godtaehee/docker-backend
  - docker push godtaehee/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-app"
  env: "Dockerfullstackapp-env-1"
  bucket_name: elasticbeanstalk-ap-northeast-2-529266148617
  bucket_path: "docker-fullstack-app"
  on:
    branch: main

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY

